### ISSUE TITLE
slabs have a full height selection box

### ISSUE THREAD

**Issue by NathanSalapat** [TumeniNodes/angledstairs#2]
Title says it all. I looked at the code and noticed you don't define a selection box, which results in everything getting a full node sized selection box. Slabs work better when they have shorter selection boxes. :)
`    selection_box = {
        type = "fixed",
        fixed = {-.5, -.5, -.5, .5, 0, .5}
    }`
I used the above code and it made it much nicer. It only needs to be added to both of the slab registrations. I could make a fork and a pull request, but I'm too lazy for that. :D

**Comment by TumeniNodes** [comment]
heh thanks Nathan. It's been so long since I made the mod, there were a few things I meant to go back and fix (this is one of them) but I forgot over time.
I will be sure to make the changes in a day or two.

**Comment by TumeniNodes** [comment]
resolved with https://github.com/TumeniNodes/angledstairs/commit/18ea4187f4cdbef6d77d80b8c363b79a6f1f8e13
Thank you again Nathan
